// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB6i0_TsyaRBBxwUOSp5Zt4lfzXcf_cFE',
    appId: '1:723611520337:web:177560dcd4299fc6d71770',
    messagingSenderId: '723611520337',
    projectId: 'greenbite-8aec0',
    authDomain: 'greenbite-8aec0.firebaseapp.com',
    storageBucket: 'greenbite-8aec0.firebasestorage.app',
    measurementId: 'G-Z7639CLNVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNwPiM0eK8JZ2c_b_ut6iQw1eolD9TMiA',
    appId: '1:723611520337:android:a773b1b51cfd3a06d71770',
    messagingSenderId: '723611520337',
    projectId: 'greenbite-8aec0',
    storageBucket: 'greenbite-8aec0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkUl0d_QrOh2MY2M3RJvTCb3QZVx-X1JM',
    appId: '1:723611520337:ios:8b99e5baa5ac8a53d71770',
    messagingSenderId: '723611520337',
    projectId: 'greenbite-8aec0',
    storageBucket: 'greenbite-8aec0.firebasestorage.app',
    iosBundleId: 'com.example.greenBite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkUl0d_QrOh2MY2M3RJvTCb3QZVx-X1JM',
    appId: '1:723611520337:ios:8b99e5baa5ac8a53d71770',
    messagingSenderId: '723611520337',
    projectId: 'greenbite-8aec0',
    storageBucket: 'greenbite-8aec0.firebasestorage.app',
    iosBundleId: 'com.example.greenBite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB6i0_TsyaRBBxwUOSp5Zt4lfzXcf_cFE',
    appId: '1:723611520337:web:09e3e44df1c8e593d71770',
    messagingSenderId: '723611520337',
    projectId: 'greenbite-8aec0',
    authDomain: 'greenbite-8aec0.firebaseapp.com',
    storageBucket: 'greenbite-8aec0.firebasestorage.app',
    measurementId: 'G-LKFRPV874S',
  );

}